# Generated by Django 4.2.23 on 2025-06-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin_padron', 'Administrador del Padrón'), ('admin_elecciones', 'Administrador de Elecciones'), ('jurado', 'Jurado Electoral')], max_length=30, unique=True)),
            ],
        ),
    ]
