# Generated by Django 5.2.4 on 2025-07-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='papeleta',
            name='mesa_id',
            field=models.IntegerField(default=0),
        ),
    ]
