# Generated by Django 5.2.4 on 2025-07-10 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0002_papeleta_mesa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='papeleta',
            name='elector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='votacion.elector'),
            preserve_default=False,
        ),
    ]
