# Generated by Django 5.2.3 on 2025-07-02 23:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('foto_ci_anverso', models.ImageField(upload_to='cis/anverso/')),
                ('foto_ci_reverso', models.ImageField(upload_to='cis/reverso/')),
                ('foto_votante', models.ImageField(upload_to='votantes/')),
                ('recinto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='padron.recinto')),
            ],
        ),
    ]
