# Generated by Django 5.2.3 on 2025-07-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recinto',
            name='latitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='recinto',
            name='longitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
